version: '2'
services:
  nginx:
    container_name: bs-static
    image: nginx:1.10.2-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../dist:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
